### ISSUE TITLE
flash attention?

### ISSUE THREAD

**Issue by lior007** [ostris/ai-toolkit#89]
UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)

**Comment by DarkAlchy** [comment]
If on windows FA2 is not available.

**Comment by brappier** [comment]
do pip install --upgrade torch==1.0.0

**Comment by DarkAlchy** [comment]
> do pip install --upgrade torch==1.0.0

Why are you going back to torch V1 when the files this needs is demanding Torch 2.4.0?  Even I had to upgrade it from 2.1.2.

**Comment by jaretburkett** [comment]
This should be resolved with reinstalling torch. Follow instructions here and install the latest version https://pytorch.org/get-started/locally/

**Comment by MichaMaGit** [comment]
I uninstalled torch and reinstalled everything
"pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121"
Still getting this error.
Training with 17 Images takes 5:30 hours - is this normal? RTX 3090 - example settings for 24gb 
thx

**Comment by DarkAlchy** [comment]
FA2 isn't on Windows unless you compile it in.  I tried Linux with FA2 and no help in speed as the only speed increase I received (in ComfyUI and Kohya) was due to Linux itself, not because it has FA2.  I expected huge gains (due to the FA2 hype on their own page) but was severely disappointed.
